version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: reactive-resume
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
  reactive-resume:
    build:
      context: .
    container_name: reactive-resume
    ports: 
      - 3000:3000
      - 4000:4000
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  database:
